### ISSUE TITLE
Fatal error: concurrent map writes

### ISSUE THREAD

**Issue by sesh-kebab** [zpatrick/fireball#6]
There are intermittent `concurrent map write` errors that occur when using fireball router. The stack trace below, indicates it is occurring with the route cache logic. I was able to reproduce it by sending a lot of GET requests to an endpoint. But is is an intermittent error so I don't know how much benefit there maybe to get consistent reproducible steps (if it is even possible).

```
2018/03/27 22:22:19 [INFO] Listening on port 9090
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 87 [running]:
runtime.throw(0x1b01774, 0x15)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:619 +0x81 fp=0xc420269c00 sp=0xc420269be0 pc=0x102b361
runtime.mapassign_faststr(0x1942440, 0xc420349410, 0xc42034e048, 0x4, 0x22c2720)
        /usr/local/Cellar/go/1.10/libexec/src/runtime/hashmap_fast.go:703 +0x3e9 fp=0xc420269c70 sp=0xc420269c00 pc=0x100d5c9
github.com/quintilesims/layer0/vendor/github.com/zpatrick/fireball.(*BasicRouter).Match(0xc420399280, 0xc42042a000, 0x1bb0360, 0xc4203782a0, 0xc42042a000)
        /Users/schemudugunta/go/src/github.com/quintilesims/layer0/vendor/github.com/zpatrick/fireball/router.go:54 +0x10d fp=0xc420269cd0 sp=0xc420269c70 pc=0x140d6cd
github.com/quintilesims/layer0/vendor/github.com/zpatrick/fireball.(*App).ServeHTTP(0xc4204de380, 0x1bb0360, 0xc4203782a0, 0xc42042a000)
        /Users/schemudugunta/go/src/github.com/quintilesims/layer0/vendor/github.com/zpatrick/fireball/app.go:40 +0xac fp=0xc420269d18 sp=0xc420269cd0 pc=0x140c4ec
net/http.(*ServeMux).ServeHTTP(0x22a4020, 0x1bb0360, 0xc4203782a0, 0xc42042a000)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:2337 +0x130 fp=0xc420269d58 sp=0xc420269d18 pc=0x1265f50
net/http.serverHandler.ServeHTTP(0xc420445ee0, 0x1bb0360, 0xc4203782a0,0xc42042a000)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:2694 +0xbc fp=0xc420269d88 sp=0xc420269d58 pc=0x1266ffc
net/http.(*conn).serve(0xc4205ce500, 0x1bb09a0, 0xc4204ac040)
        /usr/local/Cellar/go/1.10/libexec/src/net/http/server.go:1830 +0x651 fp=0xc420269fc8 sp=0xc420269d88 pc=0x1263201
runtime.goexit()
```

The underlying logic that does maps writes seems to be incorrect as it does not account for concurrent map writes. This blog post seems to have good information on how to handle concurrent access to a map, https://blog.golang.org/go-maps-in-action.

Specifically using a `sync.RWMutex`
```go
// This statement declares a counter variable that is an anonymous struct 
// containing a map and an embedded sync.RWMutex.
var counter = struct{
    sync.RWMutex
    m map[string]int
}{m: make(map[string]int)}

// To read from the counter, take the read lock:
counter.RLock()
n := counter.m["some_key"]
counter.RUnlock()
fmt.Println("some_key:", n)

// To write to the counter, take the write lock:
counter.Lock()
counter.m["some_key"]++
counter.Unlock()
```

**Comment by sesh-kebab** [comment]
This was actually fixed since `go-cache` was introduced. Was looking at an older version of the source.

**Comment by zpatrick** [comment]
This is a duplicate https://github.com/zpatrick/fireball/issues/4 and has already been fixed. I'd recommend checking that you have the latest version of fireball locally.
